"""empty message

Revision ID: 09b72eb394b3
Revises: 3d6b51654434
Create Date: 2025-08-05 09:39:22.459489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09b72eb394b3'
down_revision = '3d6b51654434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
