"""empty message

Revision ID: 0b1da85206e5
Revises: 5f470c15473e
Create Date: 2025-08-13 15:14:32.156248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b1da85206e5'
down_revision = '5f470c15473e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index('ix_eventos_atendente')
        batch_op.drop_index('ix_eventos_data')

    op.drop_table('eventos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('atendente', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_atendente', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('evento', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('parametro', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('nome_pausa', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_inicio', mysql.DATETIME(), nullable=False),
    sa.Column('data_fim', mysql.DATETIME(), nullable=False),
    sa.Column('sinaliza_duracao', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('duracao', mysql.DATETIME(), nullable=True),
    sa.Column('complemento', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_importacao', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index('ix_eventos_data', ['data'], unique=False)
        batch_op.create_index('ix_eventos_atendente', ['atendente'], unique=False)

    # ### end Alembic commands ###
