"""add achievment code

Revision ID: 19103bac13a9
Revises: 73ddd1559888
Create Date: 2025-09-13 08:02:02.477178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19103bac13a9'
down_revision = '73ddd1559888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_code', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_insignias_achievement_code'), ['achievement_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insignias_achievement_code'))
        batch_op.drop_column('achievement_code')

    # ### end Alembic commands ###
