"""empty message

Revision ID: 209221e3cfa5
Revises: 73dc821d6f12
Create Date: 2025-12-15 04:02:27.840112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '209221e3cfa5'
down_revision = '73dc821d6f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='missiondifficultyenum'), nullable=False))
        batch_op.add_column(sa.Column('mission_type', sa.Enum('QUIZ', 'GAME', 'ACTION', 'PASSIVE', name='missiontypeenum'), nullable=False))
        batch_op.add_column(sa.Column('xp_reward', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_templates', schema=None) as batch_op:
        batch_op.drop_column('xp_reward')
        batch_op.drop_column('mission_type')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
