"""add perfection_bonus em pw

Revision ID: 245b7f95779b
Revises: ed1ccdbb882f
Create Date: 2025-12-12 02:24:03.248821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245b7f95779b'
down_revision = 'ed1ccdbb882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfection_bonus', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_attempts', schema=None) as batch_op:
        batch_op.drop_column('perfection_bonus')

    # ### end Alembic commands ###
