"""empty message

Revision ID: 34ca5391b31d
Revises: 757e261994f6
Create Date: 2025-08-13 11:12:49.405229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ca5391b31d'
down_revision = '757e261994f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_chamadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_importacao', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_chamadas', schema=None) as batch_op:
        batch_op.drop_column('data_importacao')

    # ### end Alembic commands ###
