"""empty message

Revision ID: 3512d392111c
Revises: 6772e9b31fc9
Create Date: 2025-08-07 11:25:54.250742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3512d392111c'
down_revision = '6772e9b31fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.alter_column('bloqueado',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupos', schema=None) as batch_op:
        batch_op.alter_column('bloqueado',
               existing_type=sa.String(length=20),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
