"""empty message

Revision ID: 35aa54e8d612
Revises: 4d7f6e16a35f
Create Date: 2025-07-31 12:24:53.837207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35aa54e8d612'
down_revision = '4d7f6e16a35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.drop_column('operador')

    # ### end Alembic commands ###
