"""add avatar_seed to usuarios

Revision ID: 398dd01ffb88
Revises: 5ac02fa2ebe7
Create Date: 2026-02-18 12:45:31.167734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398dd01ffb88'
down_revision = '5ac02fa2ebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_seed', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('avatar_seed')

    # ### end Alembic commands ###
