"""empty message

Revision ID: 3d6b51654434
Revises: b1fa920bd838
Create Date: 2025-08-04 11:13:06.795028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d6b51654434'
down_revision = 'b1fa920bd838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ch_atendidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ch_naoatendidas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_online', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_livre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_servico', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pimprod_refeicao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_minatend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_medatend', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_maxatend', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_importacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_performance_colaboradores_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_colaboradores_operador_id'), ['operador_id'], unique=False)
        batch_op.drop_column('tempo_total_em_chamada')
        batch_op.drop_column('total_chamadas')
        batch_op.drop_column('chamadas_atendidas')
        batch_op.drop_column('chamadas_nao_atendidas')
        batch_op.drop_column('tempo_total_disponivel')
        batch_op.drop_column('chamadas_receptivas')
        batch_op.drop_column('chamadas_ativas')
        batch_op.drop_column('tempo_total_ocioso')
        batch_op.drop_column('tempo_total_pausa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_total_pausa', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tempo_total_ocioso', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chamadas_ativas', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chamadas_receptivas', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tempo_total_disponivel', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chamadas_nao_atendidas', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chamadas_atendidas', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_chamadas', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tempo_total_em_chamada', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_performance_colaboradores_operador_id'))
        batch_op.drop_index(batch_op.f('ix_performance_colaboradores_data'))
        batch_op.alter_column('data',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('data_importacao')
        batch_op.drop_column('tempo_maxatend')
        batch_op.drop_column('tempo_medatend')
        batch_op.drop_column('tempo_minatend')
        batch_op.drop_column('pimprod_refeicao')
        batch_op.drop_column('tempo_servico')
        batch_op.drop_column('tempo_livre')
        batch_op.drop_column('tempo_online')
        batch_op.drop_column('ch_naoatendidas')
        batch_op.drop_column('ch_atendidas')
        batch_op.drop_column('operador_id')

    # ### end Alembic commands ###
