"""empty message

Revision ID: 3f942a55ee16
Revises: 245b7f95779b
Create Date: 2025-12-14 08:35:05.822600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f942a55ee16'
down_revision = '245b7f95779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spec_bonus', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_attempts', schema=None) as batch_op:
        batch_op.drop_column('spec_bonus')

    # ### end Alembic commands ###
