"""empty message

Revision ID: 572ecae374d4
Revises: f17d845b5b18
Create Date: 2025-12-11 16:47:33.558237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572ecae374d4'
down_revision = 'f17d845b5b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_sla_atendimento', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('status_sla_resolucao', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_column('status_sla_resolucao')
        batch_op.drop_column('status_sla_atendimento')

    # ### end Alembic commands ###
