"""allow nullable guardian_id in quizatt

Revision ID: 5ac02fa2ebe7
Revises: c6244f7caad2
Create Date: 2026-02-17 21:11:33.705776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac02fa2ebe7'
down_revision = 'c6244f7caad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('guardian_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_guardian_id'), ['guardian_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_guardian_id'))
        batch_op.alter_column('guardian_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
