"""empty message

Revision ID: 5ac5ad72eab6
Revises: b6a21220fe30
Create Date: 2025-12-24 18:42:12.917151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac5ad72eab6'
down_revision = 'b6a21220fe30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfect_minigame_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('perfect_minigame_streak')

    # ### end Alembic commands ###
