"""add patrulha diaria

Revision ID: 5ca5d07488ec
Revises: 
Create Date: 2025-09-10 13:26:31.430370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca5d07488ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_patrol_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('last_patrol_date')

    # ### end Alembic commands ###
