"""empty message

Revision ID: 5f470c15473e
Revises: 34ca5391b31d
Create Date: 2025-08-13 15:13:45.695063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f470c15473e'
down_revision = '34ca5391b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_chamadas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_chamadas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_hora', mysql.DATETIME(), nullable=True),
    sa.Column('unique_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('numero', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tempo_espera', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tempo_atendimento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nome_atendente', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('motivo', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sub_motivo', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('desconexao_local', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('data_importacao', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
