"""empty message

Revision ID: 65e73ffc2131
Revises: 35aa54e8d612
Create Date: 2025-08-01 15:04:14.210935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e73ffc2131'
down_revision = '35aa54e8d612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_colaboradores', schema=None) as batch_op:
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
