"""Adiciona started_at a QuizAttempt

Revision ID: 6a9381a951cd
Revises: d5c8c1f500d8
Create Date: 2025-09-14 11:47:20.693639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9381a951cd'
down_revision = 'd5c8c1f500d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
