"""empty message

Revision ID: 73dc821d6f12
Revises: 3f942a55ee16
Create Date: 2025-12-15 02:19:00.450035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73dc821d6f12'
down_revision = '3f942a55ee16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_shop_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('current_items_ids', sa.JSON(), nullable=False),
    sa.Column('reroll_count', sa.Integer(), nullable=True),
    sa.Column('last_refresh_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_id')
    )
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rarity', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_column('rarity')

    op.drop_table('guardian_shop_states')
    # ### end Alembic commands ###
