"""add tutorials seen em guardians

Revision ID: 740cbc727a8a
Revises: 5ac5ad72eab6
Create Date: 2025-12-25 17:35:47.992147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740cbc727a8a'
down_revision = '5ac5ad72eab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorials_seen', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('tutorials_seen')

    # ### end Alembic commands ###
