"""empty message

Revision ID: 757e261994f6
Revises: de6f3ae4cb11
Create Date: 2025-08-08 14:25:40.566136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757e261994f6'
down_revision = 'de6f3ae4cb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_importacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desempenho_atendente_vyrtos', schema=None) as batch_op:
        batch_op.drop_column('data_importacao')

    # ### end Alembic commands ###
