"""Adiciona perfect_quiz_streak aos Guardians

Revision ID: 8d1f53d751ce
Revises: d51333b24d33
Create Date: 2025-09-14 07:52:24.916940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1f53d751ce'
down_revision = 'd51333b24d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfect_quiz_streak', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('perfect_quiz_streak')

    # ### end Alembic commands ###
