"""add novo modelo para multiplas conquistas em destaque

Revision ID: 966441d1983f
Revises: b30e4f751888
Create Date: 2025-12-22 11:42:47.132524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966441d1983f'
down_revision = 'b30e4f751888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_featured',
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('insignia_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=True),
    sa.Column('equipado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['insignia_id'], ['insignias.id'], ),
    sa.PrimaryKeyConstraint('guardian_id', 'insignia_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardian_featured')
    # ### end Alembic commands ###
