"""empty message

Revision ID: 9d08b766bf1f
Revises: ff3a57446202
Create Date: 2025-08-22 11:32:17.149314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d08b766bf1f'
down_revision = 'ff3a57446202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pimprod_Lanche_5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pimprod_Pessoal_6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pimprod_Toalete_1', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.drop_column('pimprod_Toalete_1')
        batch_op.drop_column('pimprod_Pessoal_6')
        batch_op.drop_column('pimprod_Lanche_5')

    # ### end Alembic commands ###
