"""empty message

Revision ID: b068f0588220
Revises: 19a20d1f8277
Create Date: 2025-09-26 16:30:31.733098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b068f0588220'
down_revision = '19a20d1f8277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matutino_inicio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('matutino_final', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vespertino_inicio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vespertino_final', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('noturno_inicio', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('noturno_final', sa.String(length=20), nullable=True))
        batch_op.drop_column('matutino')
        batch_op.drop_column('vespertino')
        batch_op.drop_column('noturno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noturno', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('vespertino', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('matutino', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('noturno_final')
        batch_op.drop_column('noturno_inicio')
        batch_op.drop_column('vespertino_final')
        batch_op.drop_column('vespertino_inicio')
        batch_op.drop_column('matutino_final')
        batch_op.drop_column('matutino_inicio')

    # ### end Alembic commands ###
