"""empty message

Revision ID: b1fa920bd838
Revises: 65e73ffc2131
Create Date: 2025-08-04 11:10:54.441735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1fa920bd838'
down_revision = '65e73ffc2131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_chamadas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chamadas_atendidas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chamadas_nao_atendidas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chamadas_receptivas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chamadas_ativas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tempo_total_ocioso', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tempo_total_em_chamada', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tempo_total_pausa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tempo_total_disponivel', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index('ix_performance_colaboradores_data')
        batch_op.drop_index('ix_performance_colaboradores_operador_id')
        batch_op.drop_column('data_importacao')
        batch_op.drop_column('tempo_livre')
        batch_op.drop_column('tempo_minatend')
        batch_op.drop_column('tempo_servico')
        batch_op.drop_column('operador_id')
        batch_op.drop_column('tempo_maxatend')
        batch_op.drop_column('tempo_online')
        batch_op.drop_column('ch_naoatendidas')
        batch_op.drop_column('pimprod_refeicao')
        batch_op.drop_column('tempo_medatend')
        batch_op.drop_column('ch_atendidas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ch_atendidas', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_medatend', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pimprod_refeicao', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ch_naoatendidas', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_online', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_maxatend', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('operador_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tempo_servico', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_minatend', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_livre', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_importacao', mysql.DATETIME(), nullable=True))
        batch_op.create_index('ix_performance_colaboradores_operador_id', ['operador_id'], unique=False)
        batch_op.create_index('ix_performance_colaboradores_data', ['data'], unique=False)
        batch_op.alter_column('data',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('tempo_total_disponivel')
        batch_op.drop_column('tempo_total_pausa')
        batch_op.drop_column('tempo_total_em_chamada')
        batch_op.drop_column('tempo_total_ocioso')
        batch_op.drop_column('chamadas_ativas')
        batch_op.drop_column('chamadas_receptivas')
        batch_op.drop_column('chamadas_nao_atendidas')
        batch_op.drop_column('chamadas_atendidas')
        batch_op.drop_column('total_chamadas')

    # ### end Alembic commands ###
