"""add avater_seed em guardians

Revision ID: b30e4f751888
Revises: 209221e3cfa5
Create Date: 2025-12-18 05:23:23.928126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b30e4f751888'
down_revision = '209221e3cfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_seed', sa.String(length=100), nullable=True))
        batch_op.drop_column('avatar_config')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_config', mysql.JSON(), nullable=True))
        batch_op.drop_column('avatar_seed')

    # ### end Alembic commands ###
