"""empty message

Revision ID: ba98762cdfe8
Revises: 
Create Date: 2025-09-19 14:52:58.249463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba98762cdfe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insignias_achievement_code'), ['achievement_code'], unique=True)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_limit_seconds')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('started_at')

    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insignias_achievement_code'))

    # ### end Alembic commands ###
