"""Altera time_limit de minutos para segundos

Revision ID: bf431896e6ad
Revises: 6a9381a951cd
Create Date: 2025-09-14 13:20:55.382423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf431896e6ad'
down_revision = '6a9381a951cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
        batch_op.drop_column('time_limit_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('time_limit_seconds')

    # ### end Alembic commands ###
