"""add external_user_id to quiz_att

Revision ID: c6244f7caad2
Revises: 4494e23374d8
Create Date: 2026-02-17 20:58:42.651390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6244f7caad2'
down_revision = '4494e23374d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['external_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('external_user_id')

    # ### end Alembic commands ###
