"""add anonimato no banco

Revision ID: d51333b24d33
Revises: 19103bac13a9
Create Date: 2025-09-13 15:38:22.828215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51333b24d33'
down_revision = '19103bac13a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insignias_achievement_code'), ['achievement_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insignias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insignias_achievement_code'))

    # ### end Alembic commands ###
