"""Adiciona time_limit_minutes aos Quizzes

Revision ID: d5c8c1f500d8
Revises: 8d1f53d751ce
Create Date: 2025-09-14 11:11:07.319207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c8c1f500d8'
down_revision = '8d1f53d751ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('time_limit_minutes')

    # ### end Alembic commands ###
