"""empty message

Revision ID: de6f3ae4cb11
Revises: 3512d392111c
Create Date: 2025-08-08 10:47:24.510265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6f3ae4cb11'
down_revision = '3512d392111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_operador_data', ['operador_id', 'data'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_operador_data', type_='unique')

    # ### end Alembic commands ###
