"""empty message

Revision ID: e19d286a9630
Revises: 0b1da85206e5
Create Date: 2025-08-13 15:16:04.895032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e19d286a9630'
down_revision = '0b1da85206e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fila')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fila',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('chamadas_completadas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chamadas_abandonadas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transbordo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chamadas_recebidas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tempo_espera', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tempo_fala', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nivel_servico', mysql.FLOAT(), nullable=True),
    sa.Column('data', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
