"""add last spec change ao guardians

Revision ID: ed1ccdbb882f
Revises: 1afd8b604878
Create Date: 2025-12-10 05:02:56.680599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1ccdbb882f'
down_revision = '1afd8b604878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_spec_change_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('last_spec_change_at')

    # ### end Alembic commands ###
