"""empty message

Revision ID: f17d845b5b18
Revises: 
Create Date: 2025-10-01 12:46:15.974584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f17d845b5b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalhes_chamadas', schema=None) as batch_op:
        batch_op.alter_column('transferencia',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('rotuloSubMotivo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('subMotivo',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('isAtendida',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('isAbandonada',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTempo',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTecla',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('Nome',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('protocolo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalhes_chamadas', schema=None) as batch_op:
        batch_op.alter_column('protocolo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('Nome',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTecla',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTempo',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('isAbandonada',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('isAtendida',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('subMotivo',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('rotuloSubMotivo',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('transferencia',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
