"""empty message

Revision ID: ff3a57446202
Revises: eb31b5227deb
Create Date: 2025-08-15 16:21:27.951253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff3a57446202'
down_revision = 'eb31b5227deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalhes_chamadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataImportacao', sa.String(length=50), nullable=True))
        batch_op.alter_column('idFila',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('nomeFila',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('uniqueID',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('origem',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tipoOrigem',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('filaOrigem',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('horaEntradaPos',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('horaAtendimento',
               existing_type=mysql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('horaTerminoPos',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tempoEspera',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tempoAtendimento',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('numeroAtendente',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('nomeAtendente',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('desconexaoLocal',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('transferencia',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('rotuloSubMotivo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('subMotivo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('isAtendida',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('isAbandonada',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTempo',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTecla',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('isIncompleta',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('numeroSemFormato',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('Nome',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('protocolo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('retentativaSucesso',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalhes_chamadas', schema=None) as batch_op:
        batch_op.alter_column('retentativaSucesso',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('protocolo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('Nome',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('numeroSemFormato',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('isIncompleta',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTecla',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('isTransbordoPorTempo',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('isAbandonada',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('isAtendida',
               existing_type=sa.String(length=10),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
        batch_op.alter_column('subMotivo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('rotuloSubMotivo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('motivo',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('transferencia',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('desconexaoLocal',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('nomeAtendente',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('numeroAtendente',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('tempoAtendimento',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('tempoEspera',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('horaTerminoPos',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('horaAtendimento',
               existing_type=sa.String(length=50),
               type_=mysql.TIME(),
               existing_nullable=True)
        batch_op.alter_column('horaEntradaPos',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('filaOrigem',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipoOrigem',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('origem',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('uniqueID',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nomeFila',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('idFila',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('dataImportacao')

    # ### end Alembic commands ###
