"""empty message

Revision ID: ffcefd07c59c
Revises: 966441d1983f
Create Date: 2025-12-22 11:54:00.663882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffcefd07c59c'
down_revision = '966441d1983f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_constraint('guardians_ibfk_1', type_='foreignkey')
        batch_op.drop_column('featured_insignia_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_insignia_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('guardians_ibfk_1', 'insignias', ['featured_insignia_id'], ['id'])

    # ### end Alembic commands ###
